name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-ormolu@v17
        with:
          pattern: app/**/*.hs
      - uses: haskell-actions/hlint-setup@v2
      - uses: haskell-actions/hlint-run@v2
        with:
          path: app/
          fail-on: warning

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          cache-from: type=gha,scope=kio-ssh
          cache-to: type=gha,scope=kio-ssh,mode=max
